### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by chen0gao** [chen0gao/bay-area-hacks-2023#8]
https://www.codementor.io/projects/web/medicine-dose-tracker-b6evlas194
Challengge: database

1. Timer
2. database
Medicine
- medicine basebase
  - look data
  - update data
- Other track
  - user built basebase
    - input (leetcode Qs, hw)
       -highlight mistake
       -last submission date
       -testing/see high level
       -reminder to practice
3. virtual reward points

**Comment by eh668** [comment]
1. Timer: Build using javascript
- Countdown timer: https://freshman.tech/pomodoro-timer/
- Alarm clock: https://contactmentor.com/build-alarm-clock-javascript/

2. Database:
User built database: 
- Create a form so the user can manually enter info about their LC questions, homework to do...etc
- Pull user's LC data from LC using an API: https://github.com/JeremyTsaii/leetcode-stats-api
